name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          USER_AGENT="3bsalam-1"
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER="3bsalam-1
          REPO_NAME="3bsalam-1"
          BASE_BRANCH="main"
          NEW_BRANCH="automated-pull-request"
          TITLE="Automated Pull Request"
          MESSAGE="This pull request is automatically created by a user."
          COMMIT_MESSAGE="Create ${NEW_BRANCH} branch"

          # Create a new branch
          git checkout -b ${NEW_BRANCH}
          git push -u origin ${NEW_BRANCH}

          # Create a new pull request
          git config --global user.email "actions@github.com"
          git config --global user.name "${USER_AGENT}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "User-Agent: ${USER_AGENT}" \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls \
            -d "{\"title\":\"${TITLE}\", \"body\":\"${MESSAGE}\", \"head\":\"${REPO_OWNER}:${NEW_BRANCH}\", \"base\":\"${BASE_BRANCH}\"}"

          # Clean up
          git checkout main
          git branch -D ${NEW_BRANCH}
          git push origin --delete ${NEW_BRANCH}