name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Automated Pull Request";
            const body = "This pull request is automatically created by a user.";
            const base = "main";
            const head = "automated-pull-request";

            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              base,
              head,
            });

            console.log(`Pull request created: ${pullRequest.html_url}`);
