name: Open Pull Request
 
on:
  push:
    branches:
      - main
  schedule:
  - cron: "1 * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Set up Git
        run: |
          git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git checkout -b main
          git add .
          git commit -m "Add new feature"
          git push origin feature-branch
          gh pr create --title "New Feature" --body "Please review this pull request" --base main --head feature-branch
